version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: db
      APP_KEY:
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      DB_PORT: 3306
    working_dir: /var/www
    networks:
      - app-network
      - dbnet

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443


  #MySQL Service
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - dbnet

#Docker Networks
networks:
  app-network:
    driver: bridge
  dbnet:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
